run:
  timeout: 5m
  tests: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - revive

linters-settings:
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/Krive/ServiceNow-Toolkit

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - dupl
    - path: examples/
      linters:
        - gosec
